- name: nginx install and run
  hosts: frontend
  become: yes
  tasks:
    - name: install nginx server
      ansible.builtin.package:
        name: nginx
        state: present
    - name: run nginx service
      ansible.builtin.service:
        name: nginx
        state: started