- name: understand vars preferance
  hosts: local
  connection: local
  vars:
    GREETING: "Hello from PLAY"
  vars_files:
    - COURSE.yaml
  vars_prompt:
    - name: GREETING
      prompt: please enter greeting
      private: true
  tasks:
  - name: print the greeting
    vars:
      GREETING: "Hello from TASK"
    ansible.builtin.debug:
      msg: " {{ GREETING }}"